image: centos7-for-kvrocks
# image: centos6-for-kvrocks
stages:
    - build
    - test
    - pkg
    - release

build:
    stage: build
    only:
        - master
        - tags
        - merge_requests
    tags:
        - dev
    script:
        - rm -rf /cache/unittest
        - cpplint --linelength=120 --filter=-build/include_subdir,-legal/copyright,-build/c++11 src/*.h src/*.cc
        - git submodule init && git submodule update
        - mkdir build/
        - cd build && cmake -DCMAKE_BUILD_DIRECTORY=/cache/build -DCMAKE_BUILD_TYPE=Release .. && make -j4 && cd ..
        - mkdir -p _build/bin && cp build/kvrocks _build/bin
        - mkdir -p _build/conf && cp kvrocks.conf _build/conf
        - cp build/unittest /cache # reuse unittest in test stage
    artifacts:
        name: "kvrocks-${CI_PIPELINE_ID}-build"
        paths:
            - _build/
        expire_in: "3 days"
        
unittest:
    stage: test
    only:
        - master
        - tags
        - merge_requests
    tags:
        - dev
        
    script:
        - /cache/unittest
    
    dependencies:
        - build
        
rpm:
    stage: pkg
    image: packager
    only:
        - tags
    tags:
        - dev
    script:
        - bash package.sh
    artifacts:
        name: "kvrocks-${CI_PIPELINE_ID}-rpm"
        paths:
            - "*.rpm"
        expire_in: "1 week"
    dependencies:
        - build
        - unittest

release:
    stage: release
    image: rsync
    only:
        - tags

    tags:
        - dev
    script:
        - mkdir _sync && cp -v *.rpm _sync
        - cd _sync && rsync -avz . 172.16.28.10::rpmRepo/
    when: manual
    dependencies:
        - rpm

