image: centos7-for-kvrocks
# image: centos6-for-kvrocks
stages:
    - analysis
    - build
    - test
    - pkg
    - release

code_analysis:
    tags:
        - dev
    stage: analysis
    script:
        - sh cpplint.sh
        - sh cppcheck.sh

build:
    stage: build
    tags:
        - dev
    script:
        - rm -rf /cache/unittest
        - git submodule init && git submodule update
        - mkdir build/
        - cd build && cmake -DCMAKE_BUILD_DIRECTORY=/cache/build -DCMAKE_BUILD_TYPE=Release .. && make -j4 && cd ..
        - mkdir -p _build/bin && cp build/kvrocks _build/bin
        - mkdir -p _build/conf && cp kvrocks.conf _build/conf
        - cp build/unittest /cache # reuse unittest in test stage
        - cp build/kvrocks /cache # reuse kvrocks in test stage
    artifacts:
        name: "kvrocks-${CI_PIPELINE_ID}-build"
        paths:
            - _build/
        expire_in: "3 days"

    dependencies:
        - code_analysis
        
unittest:
    stage: test
    tags:
        - dev
        
    script:
        - /cache/unittest
    
    dependencies:
        - build

function-test:
    stage: test
    tags:
        - dev

    script:
        - pip install nose && pip install git+https://github.com/andymccurdy/redis-py.git@2.10.6
        - mkdir /data
        - sh tests/scripts/start_master.sh
        - sh tests/scripts/start_slave.sh
        - cd tests/functional && nosetests -v

    dependencies:
        - build

rpm:
    stage: pkg
    image: packager
    only:
        - tags
    tags:
        - dev
    script:
        - bash package.sh
    artifacts:
        name: "kvrocks-${CI_PIPELINE_ID}-rpm"
        paths:
            - "*.rpm"
        expire_in: "1 week"
    dependencies:
        - build
        - unittest
        - function-test

release:
    stage: release
    image: rsync
    only:
        - tags

    tags:
        - dev
    script:
        - mkdir _sync && cp -v *.rpm _sync
        - cd _sync && rsync -avz . 172.16.28.10::rpmRepo/
    when: manual
    dependencies:
        - rpm

